### ISSUE TITLE
add possibility to ignore classes

### ISSUE THREAD

**Issue by nidi3** [nidi3/code-assert#10]

**Comment by axelfontaine** [comment]
The ability to ignore generated code would be great. (`target/generated-sources`)

**Comment by nidi3** [comment]
I introduced `DependencyCollector`, so you can filter dependency issues like other issue types:
````
DependencyCollector collector = new DependencyCollector().just(In.loc("my.package")).ignoreAll());
DependencyResult result = new DependencyAnalyzer(config, rules, Scope.PACKAGES, collector).analyze();
assertThat(result, matchesExactly());
````
Does this solve your issue?

**Comment by nidi3** [comment]
It filters on package name, not source code directory, but I think it's good practice to use a separate package for generated code anyways.

**Comment by axelfontaine** [comment]
Yes, package name is even better, because with Maven both regular and generated classed end up in `target/classes`.

**Comment by axelfontaine** [comment]
Any release planned in the near future that would include this? (I am asking as I'll most likely be mentioning your library in my talk about modularization at JavaZone 10 days from now and it would be great to not have to include fineprint when recommending it)

**Comment by nidi3** [comment]
Never heard of JavaZone, but seems nice.
I'd like to make a release today, including your last maven issue.

**Comment by nidi3** [comment]
Finally, it's released

**Comment by axelfontaine** [comment]
Hmm I just came around to testing this and it appears one still can't ignore packages when detecting cycles. Or am I mistaken?

**Comment by nidi3** [comment]
Oh, your're right, I missed the cycles.
Hope to fix it this weekend.

**Comment by nidi3** [comment]
Next try.

**Comment by axelfontaine** [comment]
Thanks. Could you add an example to the docs or at least some JavaDoc as I must admit I really have no clue how to use the new API to exclude a package. Thanks!

**Comment by nidi3** [comment]
That's unfortunate.
It would be something like 
```
assertThat(new DependencyAnalyzer(config)
  .collector(new DependencyCollector()
    .just(In.loc("my.package").ignore(DependencyCollector.CYCLE))
  .analyze(), hasNoCycles())
```
