### ISSUE TITLE
add support for findbugs-sec

### ISSUE THREAD

**Issue by javabeanz** [nidi3/code-assert#22]
http://find-sec-bugs.github.io/ or is it suppored already ?

**Comment by javabeanz** [comment]
well ?

**Comment by nidi3** [comment]
Findbug plugins will be picked up automatically from the classpath in the next version. 
Findbugs-sec will be included as a dependency.
I hope I can release this today.

**Comment by javabeanz** [comment]
that would be great Stefan, thanks !
