### ISSUE TITLE
Externals should fail dependency rules if not used

### ISSUE THREAD

**Issue by axelfontaine** [nidi3/code-assert#24]
For example, adding `javax.*` should not cause the check to fail if no javax class was used.

This would make it much easier to define a set of generic base rules for all modules in a project.

**Comment by nidi3** [comment]
What do you mean exactly? 
Do you have an example?
`DependencyRules.withExternals("javax*")` means that all javax classes are allowed to be used

**Comment by axelfontaine** [comment]
Sorry about the confusion. My report was missing a crucial "no" (fixed now).

Yes so the issue that currently they *must* be used instead of simply being allowed to be used.

**Comment by nidi3** [comment]
Ok, I see
