### ISSUE TITLE
Improve Maven module detection

### ISSUE THREAD

**Issue by axelfontaine** [nidi3/code-assert#25]
Currently running the same test (part of a multi-module Maven Project) produces different results in IntelliJ and Maven due to different working directories.

I have worked around it as follows:

```java
AnalyzerConfig config;
if (module.equals(Paths.get(".").toAbsolutePath().normalize().toFile().getName())) {
    // Already within the module, no need to specify it.
    config = AnalyzerConfig.maven().main();
} else {
    config = AnalyzerConfig.maven(module).main();
}
``` 

It would be great if the `maven()` part could autodetect this correctly in order to always being able to simply use `AnalyzerConfig.maven().main()`.

**Comment by nidi3** [comment]
Hm, what's your setup?
I can run e.g. the project's own tests in maven and in intellij and they both work.

**Comment by axelfontaine** [comment]
### Versions
- **Maven** 3.5.0
- **IntelliJ** 2017.2.3
- **code-assert** 0.0.13

### Working directory when running tests
- **Maven** always uses the *current module root* as the working directory.
- **IntelliJ** uses the *project root* as the working directing.

### `AnalyzerConfig.maven().main()`
- **Maven full build**: works
- **Maven module build**: works
- **IntelliJ**: *breaks with `Invalid directory or JAR file: target/classes`*

### `AnalyzerConfig.maven(module).main()`
- **Maven full build**: *breaks with `Invalid directory or JAR file: mymodule/target/classes`*
- **Maven module build**: *breaks with `Invalid directory or JAR file: mymodule/target/classes`*
- **IntelliJ**: works

**Comment by nidi3** [comment]
Are you using windows? 
There is already a check, but probably not os-safe.

**Comment by axelfontaine** [comment]
Yes, Win 10 x64

**Comment by nidi3** [comment]
Should be fixed in 0.8.1

**Comment by axelfontaine** [comment]
This appears to still be broken in IntelliJ with 0.8.2. I still need to use my workaround with that version.

**Comment by nidi3** [comment]
I still cannot reproduce the error.
The check is here: https://github.com/nidi3/code-assert/blob/f1fd5ead162104f37c41c1879fa24f99f73fc773/code-assert/src/main/java/guru/nidi/codeassert/config/AnalyzerConfig.java#L149
Could you try and see what's going on? Thanks!

**Comment by axelfontaine** [comment]
Upon further testing, `AnalyzerConfig.maven(module).main()` now works both in Maven and IntelliJ.

`AnalyzerConfig.maven().main()` remains broken in IntelliJ, but in a different way: nothing is found! In this case the `runningInModuleDir()` method you mentioned also is not called.

**Comment by nidi3** [comment]
In this case, I guess, the working dir is the project root. Without a given `module`, how can it know the correct dir?
Btw I still cannot reproduce this. How exactly do you run the test with IntelliJ so that the working dir is not the module dir?
