### ISSUE TITLE
Codebase is empty using Gradle

### ISSUE THREAD

**Issue by RoRoche** [nidi3/code-assert#34]
Hi everybody,

here is the test I launch (in a standard IntelliJ java project built with Gradle):

```java
    @Test
    public void testFindBugs() {
        AnalyzerConfig config = AnalyzerConfig.gradle().main();
        BugCollector collector = new BugCollector();
        FindBugsResult result = new FindBugsAnalyzer(config, collector).analyze();
        MatcherAssert.assertThat(result, CodeAssertMatchers.hasNoBugs());
    }
```

but the test fails with the following stacktrace:

```java
guru.nidi.codeassert.AnalyzerException: Problem executing FindBugs.
```

and I spotted it is thrown by the following code in `Findbugs2.java` (line 273)

```java
                    } else if  (codebase.isEmpty()) {
                        throw new IOException("No files to analyze could be opened");
```

what configuration am I missing?

**Comment by RoRoche** [comment]
I'm using it in a submodule in IntelliJ.
So the sources are in `my_submodule/src/main/jaba`, the class files in `my_submodule/build/classes/java/main` and `out/production/classes`

**Comment by nidi3** [comment]
Not sure about the problem, but it's intended that every submodule has its own test.
So the main module does not see the submodules. Though, it could make sense to support this.
Is this your problem?

**Comment by nidi3** [comment]
I just saw that you can do `AnalyzerConfig config = AnalyzerConfig.gradle("my_submodule").main();`. Does this solve your problem?

**Comment by RoRoche** [comment]
Yes it works with `AnalyzerConfig config = AnalyzerConfig.gradle("my_submodule").main();`
