### ISSUE TITLE
Split code-assert into several modules

### ISSUE THREAD

**Issue by C-Otto** [nidi3/code-assert#41]
I use the code-assert module to find package cycles, which works fine. Thanks for that! However, I noticed that the code-assert module also includes several dependencies that are not necessary and, in my case, cause issues. Because of that I had to manually exclude those, and (re)add commons-io.

Please try to split the module, and/or remove dependencies. This is how I now include code-assert to find package cycles:

```
testFixturesImplementation 'commons-io:commons-io:latest.release'
testFixturesImplementation('guru.nidi:code-assert:latest.release') {
        exclude group: 'guru.nidi', module: 'graphviz-java'
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
        exclude group: 'com.github.spotbugs', module: 'spotbugs'
        exclude group: 'com.h3xstream.findsecbugs', module: 'findsecbugs-plugin'
        exclude group: 'net.sourceforge.pmd', module: 'pmd-java'
        exclude group: 'com.puppycrawl.tools', module: 'checkstyle'
        exclude group: 'io.gitlab.arturbosch.detekt', module: 'detekt-core'
        exclude group: 'io.gitlab.arturbosch.detekt', module: 'detekt-rules'
        exclude group: 'com.github.shyiko.ktlint', module: 'ktlint-core'
        exclude group: 'com.github.shyiko.ktlint', module: 'ktlint-ruleset-standard'
        exclude group: 'org.slf4j', module: 'slf4j-api'
        exclude group: 'org.slf4j', module: 'jcl-over-slf4j'
        exclude group: 'org.slf4j', module: 'jul-to-slf4j'
    }
```

**Comment by nidi3** [comment]
Split out code-assert-code in version `0.9.12`

**Comment by C-Otto** [comment]
Thank you!

**Comment by C-Otto** [comment]
Could you please explain the differences? I still see jcl-over-slf4j and jul-to-slf4j, which reconfigure my logging setup. If you want to use SLF4J, please just add the SLF4J API. Furthermore, with guru.nidi:code-assert:0.9.12 I also get dependencies related to PMD and Checkstyle, among others. I don't really see a different to before, to be honest.

Maybe I should clarify? I'd like to include code-assert (or another module) so that I can make use of the package cycle detection feature. I don't want more than that, especially the dependencies named above. If users want to use PMD and Checkstyle, I think they should use code-assert-pmd or similar (new) modules instead.

**Comment by nidi3** [comment]
I removed the 2 slf4j dependencies in version `0.9.13`.
